### DISCUSSION TITLE
Dockerization of everything

### DISCUSSION THREAD

**Discussion by ibrunotome** [magic-test/magic-test-laravel#14] [Ideas]
Would be great to have the steps to run all of it in a single docker-compose file 🙏 This will make easily to run GitHub actions with dusk tests.

**Comment by mateusjatenee** [comment]
Hmmm, I know nothing about Docker. Is that something you could PR? I honestly don't even know where to begin. 😬

**Comment by ricklambrechts** [comment]
Laravel Sail generates this in the docker-compose file.
```
    selenium:
       image: 'selenium/standalone-chrome'
       ports:
            - '${FORWARD_SELENIUM_PORT:-4444}:4444'
       volumes:
            - '/dev/shm:/dev/shm'
       networks:
            - sail
```

Then as the `DUSK_DRIVER_URL` you can use `http://selenium:4444/wd/hub`.
