### DISCUSSION TITLE
Using Magic-Test within Laravel Sail

### DISCUSSION THREAD

**Discussion by AidanLaycock** [magic-test/magic-test-laravel#21] [Q&A]
Hi, really love the package as it looks like it should really streamline dusk development for my projects.

I was just wondering if anyone had managed to get this working with Laravel Sail, as Sail runs selenium in the background for dusk tests.

**Comment by ricklambrechts** [comment]
Hi,

I have it working in Sail. But then you can only do the tests in the background.
This is how you can do that: https://github.com/magic-test/magic-test-laravel/discussions/14#discussioncomment-481375.

When you need the browser for creating a test. Then i start the chromedriver locally by `chromedriver.exe --whitelisted-ips="127.0.0.1"`.
And set the dusk `DUSK_DRIVER_URL` to `http://host.docker.internal:9515`.

**Reply by AidanLaycock** [reply]
Interesting! I shall give that a go later this week and report back :)

**Reply by mateusjatenee** [reply]
Any luck here? I don't use Sails and I have no idea how to make this run properly on it. I assume there's no way to natively make the browser open since it's inside a container, right?

**Reply by ricklambrechts** [reply]
I digged in some documentation today. 

Sail uses the `selenium/standalone-chrome` docker image. Apparently you can connect through VNC to view the chrome browser. Check https://github.com/SeleniumHQ/docker-selenium#debugging.

I thought it was only adding the port map and then connecting with an VNC viewer. But I needed to change the image also.
So i updated the Sail service in the docker-compose.yml to this, added the 5900 port and used the debug image:
```
    selenium:
       image: 'selenium/standalone-chrome-debug'
       ports:
            - '${FORWARD_SELENIUM_PORT:-4444}:4444'
            - '5900:5900'
       volumes:
            - '/dev/shm:/dev/shm'
       networks:
            - sail
```

After an `sail down` and `sail up`, I could successfully connect with VNC Viewer to `localhost:5900`. If it is asking for a password use `secret`.  Then i run `sail artisan magic` and i saw the browser appearing.

I still prefer to start a local chromedriver so i can easily resize the window.
